#Tue Nov 14 09:03:05 GMT 2023
micronaut:
  application:
    name: micronout-demo
  server:
    port: 8181
    cors:
      enabled: true
    max-request-size: '10MB'
    multipart:
      max-file-size: '10MB'
  router:
    static-resources:
      main:
        paths: classpath:views
        mapping: /main/**

datasources:
  default:
    db-type: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/santec_shop?preparedStatementCacheQueries=0
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
    dialect: POSTGRES


flyway:
  datasources:
    default:
      enabled: false

upload:
  imagePath: /home/gali/upload/images
  documentPath: /home/gali/upload/docs

apiUrl: http://161.97.144.45:8181/