#Tue Nov 14 09:03:05 GMT 2023
micronaut:
  application:
    name: micronout-demo
  server:
    port: 8180
    max-request-size: '10MB'
    multipart:
      max-file-size: '10MB'
    cors:
      enabled: true
  router:
    static-resources:
      main:
        paths: classpath:views
        mapping: /main/**


  views:
    thymeleaf:
      enabled: true


datasources:
  default:
    db-type: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/santec_shop?preparedStatementCacheQueries=0
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
    dialect: POSTGRES


flyway:
  datasources:
    default:
      enabled: true

upload:
  imagePath: /Users/gali/IdeaProjects/upload/images
  documentPath: /Users/gali/IdeaProjects/upload/docs


apiUrl: http://localhost:8180/